version: '3.8'
services:
  database:
    image: mysql:8.2.0
    container_name: db_mysql
    restart: always
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
    volumes:
      - mysql_data:/var/lib/mysql/
      - ./script/start/01_create.sql:/docker-entrypoint-initdb.d/1.sql
      - ./script/start/02_init.sql:/docker-entrypoint-initdb.d/2.sql
    networks:
      app-network:
        ipv4_address: 172.18.0.2
  # php:
  #   build:
  #     context: .
  #     dockerfile: php.Dockerfile
  #   container_name: php
  #   volumes:
  #     - ./:/app
  #   depends_on:
  #     - database
  #   networks:
  #     - app-network
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   restart: always
  #   ports:
  #     - 7070:80
  #   environment:
  #     PMA_HOST: database
  #   networks:
  #     - app-network
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "8080:80"
  #     - "1235:443"
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - php
  #   networks:
  #     - app-network

volumes:
  database_data:
  mysql_data:
networks:
  app-network:
    ipam:
      config:
        - subnet: 172.18.0.0/16
